layoutGenerator/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

# Main views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/register/", views.RegisterPage, name="register"),
    path("import/", views.ImportPage, name="import"),
    path("accounts/login/", views.LoginPage, name="login"),
    path("", RedirectView.as_view(url="import/", permanent=True)),
    path("accounts/logout/", views.LogoutPage, name='logout'),
    path('layout-library/', views.LayoutLibraryPage, name="layout-library"),
    path('default-style-settings/', views.SettingsPage, name='settings'),
    path('reset-settings/', views.reset_default_settings, name='reset-settings'),
    path('account-settings/', views.AccountSettingsPage, name='account-settings'),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('accounts/password-reset-sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    path('accounts/password-reset-confirmation/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password-reset.html'), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_confirm.html'), name='password_reset_complete'),
]

# Support serving PNG images in django app
urlpatterns += [path('serve-image/<path:image_path>/', views.serve_image, name='serve-image')]

# Downloading Sample Files
urlpatterns += [
    path('download/sample_excel/', views.download_sample_excel, name="download-sample-excel"),
    path('download/sample_csv/', views.download_sample_csv, name="download-sample-csv"),
    path('download/sample_json/', views.download_sample_json, name="download-sample-json"),
    path('download/pdf/<int:layout_id>', views.download_pdf, name='download-pdf'),
    path('download/tex/<int:layout_id>', views.download_tex, name='download-tex'),
    path('download/zip/<int:layout_id>', views.download_zip, name='download-zip'),
]

# Map to a layout's unique ID to a view function rendering idvl export page
urlpatterns += [
    path('export/<int:layout_id>', views.ExportPage, name="export-layout"),
    path('edit/<int:layout_id>', views.EditLayoutStylePage, name='edit-layout')
]

# Delete Button
urlpatterns += [
    path('delete-layout-test/<int:layout_id>/', views.delete_layout_test, name='delete_layout_test'),
    path('delete-all-layout-test/', views.delete_all_layout_test, name='delete_all_layout_test'),
]

# Serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/forms.py
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import StyleSettings, DefaultStyleSettings, ConvertedFile, Label

from django import forms
from django.forms import ModelForm

# forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User


class AccountSettingsForm(forms.ModelForm):
    """
    Form class for updating a user's account settings, including email and password changes.
    
    This form provides fields for updating the email address and/or password associated with a user's account,
    requiring the user to enter their current password twice in order to permit any changes.

    Fields:
        old_password: Field for user to enter their current (old) password
        new_password1: Field for user to enter their new password
        new_password2: Field for user to verify their new password
        email: Field for user to update email address

    Methods:
        clean(): Validation method for ensuring password criteria and verifying the user's current password

    """

    old_password = forms.CharField(label="Old Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=False)
    new_password1 = forms.CharField(label="New Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=False)
    new_password2 = forms.CharField(label="Confirm New Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=False)

    class Meta:
        model = User
        fields = ['email']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }
    
    # Ensure new passwords match given criteria & verify user's current password to allow changes
    def clean(self):
        # call parent cleaning methods
        cleaned_data = super().clean()
        old_password = cleaned_data.get('old_password')
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')
        
        # Check if user entered values within new password fields
        if new_password1 or new_password2:
            # Perform data validation on new passwords
            if len(new_password1) < 8:
                self.add_error('new_password1', 'Password must contain at least 8 characters.')
            elif new_password1.isdigit():
                self.add_error('new_password1', 'Password cannot be entirely numeric.')
            if new_password1 != new_password2:
                self.add_error('new_password2', 'The two password fields didn’t match.')
            if not old_password:
                self.add_error('old_password', 'Please enter your old password.')
            else:
                user = self.instance
                if not user.check_password(old_password):
                    self.add_error('old_password', 'The old password is incorrect.')
                elif new_password1 == old_password:
                    self.add_error('new_password1', 'The new password is the same as the old password.')
        
        return cleaned_data


class UpdateFileNameForm(ModelForm):
    """
    Form class for updating the file name of the uploaded file associated with an imported layout.

    Fields:
        new_file_name: Field for user to enter new file name

    Methods:
        clean_new_file_name(): Cleans the given file name to follow standard file naming conventions, removing leading/trailing whitespace and
        replacing spaces in the string with underscores. Performs validation to prevent duplicate file names in user's library.
    """
    new_file_name = forms.CharField(label='New file name', widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=48, required=False)

    class Meta:
        model = ConvertedFile
        fields = ['new_file_name']

    def clean_new_file_name(self):
        new_file_name = self.cleaned_data['new_file_name'].strip()  # Remove leading and trailing whitespace

        # Check if the file name is blank after stripping whitespace
        if new_file_name == "":
            print("BLANK NAME")
            raise forms.ValidationError("File name cannot be blank.")
        
        # Replace space between characters with underscores
        new_file_name = new_file_name.replace(' ', '_')

        # Extract filename prefix by removing any extensions
        if '.' in new_file_name:
            new_file_name = new_file_name.split('.')[0]

        # Check that given filename does not match an existing filename in user's layout library
        user_files = ConvertedFile.objects.filter(user=self.instance.user)
        if user_files.filter(file_name=new_file_name).exists():
            raise forms.ValidationError("File name must not match an existing file in your library.")
        
        return new_file_name

class UpdateStyleSettingsForm(forms.ModelForm):
    """
    Form class for updating an individual layout's style settings.
    
    This form provides fields for updating the border colors and widths of a layout's windows, doors, walls, and furniture. It also allows the user 
    to update the colors for sensor objects, cameras, navigation arrows, and calibration points. A user can also switch the layout's orientation between
    portrait and landscape.

    Methods:
        clean(): Validation method ensuring that all updated border widths are within the permitted values of 1 through 16.
    """
    class Meta:
        model = StyleSettings
        fields = ('wall_color', 'door_color', 'furniture_color', 'window_color',
                  'wall_width', 'door_width', 'furniture_width', 'window_width',
                  'sensor_label_color', 'camera_label_color', 'navigation_arrow_color', 'calibration_color',
                  'orientation')
        widgets = {
            'wall_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'door_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'furniture_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'window_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'sensor_label_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'camera_label_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'navigation_arrow_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'calibration_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            # border widths
            'wall_width': forms.TextInput(attrs={'class': 'form-control', 'type': 'number', 'min': 1, 'max': 16}),
            'door_width': forms.TextInput(attrs={'class': 'form-control', 'type': 'number', 'min': 1, 'max': 16}),
            'furniture_width': forms.TextInput(attrs={'class': 'form-control', 'type': 'number', 'min': 1, 'max': 16}),
            'window_width': forms.TextInput(attrs={'class': 'form-control', 'type': 'number', 'min': 1, 'max': 16}),
            }
        
    # Validate data when form is saved
    def clean(self):
            # Get data from the form
            cleaned_data = super().clean()
            wall_width = cleaned_data.get('wall_width')
            door_width = cleaned_data.get('door_width')
            furniture_width = cleaned_data.get('furniture_width')
            window_width = cleaned_data.get('window_width')

            # Check that all TextInput fields for widths contain valid number values between 1 and 16
            if wall_width is not None and (wall_width < 1 or wall_width > 16):
                 raise ValidationError('Wall width must be between 1 and 16.')
            if door_width is not None and (door_width < 1 or door_width > 16):
                raise ValidationError('Door width must be between 1 and 16.')
            if furniture_width is not None and (furniture_width < 1 or furniture_width > 16):
                raise ValidationError('Furniture width must be between 1 and 16.')
            if window_width is not None and (window_width < 1 or window_width > 16):
                raise ValidationError('Window width must be between 1 and 16.')

            return cleaned_data

class UpdateDefaultStyleSettingsForm(ModelForm):
    """
    Form class for updating a user's default style settings.
    
    This form provides fields for updating the border colors and widths for furniture, windows, doors, and walls along with the colors for sensors,
    cameras, navigation arrows, and calibration points for all future layouts generated by a user. It achieves this by updating the DefaultStyleSettings
    object associated with the current user.

    Methods:
        clean(): Validation method ensuring that all updated border widths are within the permitted values of 1 through 16.
    """
    class Meta:
        model = DefaultStyleSettings
        fields = ('wall_color', 'door_color', 'furniture_color', 'window_color',
                  'wall_width', 'door_width', 'furniture_width', 'window_width',
                  'sensor_label_color', 'camera_label_color', 'navigation_arrow_color', 'calibration_color')
        widgets = {
            'wall_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),
            'door_color': forms.Select(choices=DefaultStyleSettings.COLOR_CHOICES, attrs={'class': 'form-control, form-select'}),

templates/account-settings.html
{% extends 'base.html' %}

{% block title %} Settings {% endblock %}

{% block styling %}
<style>
    body {
        background: #ccc;
    }

    #room {
        width: 400px;
        height: 300px;
        border: 2px solid #000;
        position: relative;
    }

    .wall, .furniture, .window {
        position: absolute;
    }

    .wall {
        width: 100%;
        height: 100%;
    }

    .furniture, .window {
        width: 50px;
        height: 30px;
        background-color: #ccc;
        border: 1px solid #000;
        text-align: center;
        line-height: 30px;
    }
    .image-container {
        display: flex;
        justify-content: space-around;
        position: relative;
        margin-top: 20px;
        float: right;
        bottom: 150px;
        right: 150px;
    }
    
    /* Style for the image wrapper */
    .image-container div {
        position: relative;
        cursor: pointer;
        border: 2px solid black; /* Border color for the image */
        border-radius: 5px;
    }

    .list-group-item {
        color:#fff;
        background-color: #212529;
        border: none;
    }

    .list-group-item.active {
        color:#fff;
        border: none;
        background-color: #1B9CDB;
        font-weight: bold;
    }


    
</style>
{% endblock %}


{% block content %}

<div class="container p-0 bg-body text-body align-items-center justify-content-center mt-4" style="width: 70; height: 100; border-radius: 10px;">
    <div class="row">
        <!--Sidebar for settings-->
        <div class="col-3 bg-dark p-0" style="border-top-left-radius: 10px; border-bottom-left-radius: 10px;">
            <div class="sidebar">
                <ul class="list-group mt-5" style="border-radius:0">
                    <li class="list-group-item" id="defaultStyleSettingsTab">
                        <a class='nav-link' href="{% url 'settings' %}">Default Style Settings</a>
                    </li>
                    <li class="list-group-item active" id="accountSettingsTab">
                        <a class='nav-link' href="{% url 'account-settings' %}">Account Settings</a>
                    </li>
                </ul>
            </div>
        </div>

        <!--Account Settings main content-->
        <div class="col">
            <div class="p-5" id="accountSettings">
                <h1 class="display-6 fw-bold">Account Settings</h1>
                <hr>
                {% if messages %}
                    <div class="alert alert-success" role="alert">
                        <ul>
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <form method="post" class="account-settings">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label bold-label"><b>Email:</b></label>
                        {{ form.email }}
                        
                    </div>
                    <div class="mb-3">
                        <label for="inputPassword1" class="form-label bold-label"><b>Enter new password:</b></label>
                        {{ form.new_password1 }}
                        
                    </div>
                    <div class="mb-3">
                        <label for="inputPassword2" class="form-label bold-label"><b>Confirm new password:</b></label>
                        {{ form.new_password2 }}
                        
                    </div>
                    <div class="mb-3">
                        <label for="currentPassword" class="form-label bold-label"><b>Enter current password:</b></label>
                        {{ form.old_password }}
                        
                    </div>
                
                    <div class="mb-3 align-items-right">
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                    
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </form>
                <div class="container mt-3">
                    <div class="row justify-content-end">
                        <div class="col-auto">
                            <form id="deleteForm" action="{% url 'delete_all_layout_test' %}" method="post">
                                {% csrf_token %}
                                <button type="button" class="btn btn-md btn-danger" onclick="confirmDelete()">Clear layout library</button>
                            </form>
                        </div>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripting %}
    <script>
        function confirmDelete() {
        if (confirm("Are you sure you want to delete ALL layouts from your library? This action cannot be undone!")) {
            // If user confirms, submit the form
            document.getElementById("deleteForm").submit();
        } else {
            // If user cancels, do nothing
        }
    }
    </script>
{% endblock %}

templates/export.html
{% extends 'base.html' %}

{% block title %} Export File {% endblock %}

{% block styling %}
<style>

    /*Drop-shadow effect for buttons--> */
    .shadow-toggle:focus {
    box-shadow: 0 0 0 0.25rem rgba(134, 139, 145, 0.25); /* Add focus shadow */
    }

    .shadow-toggle.active {
        box-shadow: 0 0 0 0.25rem rgba(134, 139, 145, 0.25); /* Add active shadow */
        background-color: #f8f9fa;
    }

    .btn-orientation {
        padding: 5px;
        width: 45%;
        height: 70px;
    }

    .btn-group-subtext {
        color:cornflowerblue;
    }

</style>
<script>
    // JavaScript for selecting document orientation buttons
    document.addEventListener("DOMContentLoaded", function() {
        const landscapeButton = document.getElementById("landscapeButton");
        const portraitButton = document.getElementById("portraitButton");

        landscapeButton.addEventListener("click", function() {
            landscapeButton.classList.add("active");
            portraitButton.classList.remove("active");
        })

        portraitButton.addEventListener("click", function() {
            portraitButton.classList.add("active");
            landscapeButton.classList.remove("active");
        });
    });

</script>

<script>
    function viewImageInBrowser(imagePath) {
        // Construct the URL for the view-in-browser endpoint
        var url = "{% url 'serve-image' layout.image %}";
        
        // Open the URL in a new browser window
        window.open(url, "_blank");
    }
</script>

{% endblock %}

{% block content %}
    <div class="container" {% if layout.style_settings.orientation == "portrait" %}style="width: 75%"{% elif layout.style_settings.orientation == "landscape" %}style="width:90%"{% endif %}>
        <div class="text-center row order-md-1">
            <!-- Image preview -->
            {% if layout.style_settings.orientation == "portrait" %}
            <div class="col-lg-6 col-sm-12 mt-3 p-2 container d-flex justify-content-center align-items-center" style="max-height: 33rem">
                <div class="card" style="max-height: 100%; width: auto; border: 1px solid rgb(166, 161, 161); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
                    <img class="card-img-top" src="{% url 'serve-image' layout.image %}" style="max-height:31rem; border-radius: 10px" alt="Output Preview">
                    <center>
                        <p class="mt-4 view-in-browser" onclick="viewImageInBrowser('{{ layout.image }}')">View in browser</p>
                    </center>
                </div>
            </div>
            {% endif %}

            {% if layout.style_settings.orientation == "landscape" %}
            <div class="col-lg-6 col-md-12 mt-5 p-4 container justify-content-center align-items-center">
                <div class="card mx-5" style="max-width: 100%; height: auto; border: 1px solid rgb(166, 161, 161); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
                    <img class="card-img-top" src="{% url 'serve-image' layout.image %}" style="max-width:100%; border-radius: 10px" alt="Output Preview">
                </div>
                <center>
                    <p class="mt-4 view-in-browser" onclick="viewImageInBrowser('{{ layout.image }}')">View in browser</p>
                </center>
            </div>
            
            {% endif %}
            

            <!-- Export options-->
            <div class="col-lg-6 col-sm-12 mt-3 p-2 order-md-2">
                <div class="row d-flex justify-content-between py-3" style="border-bottom: 1px solid lightgray">
                    <div class="col-6">
                        <h2 class="fw-bold align-middle float-start" style="color: #1B9CDB">Export Layout</h2>
                    </div>
                    <div class="col-5">
                        <button type="button" id="editStyle" class="btn btn-secondary btn-md float-end" onclick="window.location.href='{% url 'edit-layout' layout.id %}'">Edit Style <i class="bi bi-arrow-right"></i></button>
                    </div>
                </div>

                <!-- Form for user to update file name-->
                <div class="mt-3 py-3 text-start">
                    <p style="font-size: x-large"><b>{{ layout.file_name }}</b></p>
                    <p style="color: #595858; font-size: medium; margin-top:-0.5rem;"><i class="bi bi-clock" style="padding-right: 4px;"></i>    <i>Last modified: </i>{{ layout.last_modified }}</p>
                    <p class="mb-3" style="color: #595858; margin-top:-0.5rem"><i class="bi bi-download" style="padding-right: 4px;"></i>   Download:</p>
                        <div class="d-flex flex-row justify-content-evenly mt-4">
                            <button type="button" class="btn download-button" onclick="window.location.href='{% url 'download-pdf' layout.id %}'"><i class="bi bi-file-pdf"></i>   PDF</button>
                            <button type="button" class="btn download-button" onclick="window.location.href='{% url 'download-tex' layout.id %}'"><i class="bi bi-file-earmark-code"></i>  TeX</button>
                            <button type="button" class="btn download-button" onclick="window.location.href='{% url 'download-zip' layout.id %}'"><i class="bi bi-file-zip"></i>  Both</button>
                        </div>
                        
                        <div class="mt-5 text-start">
                            {% if update_file_name_form.errors %}
                            <div class="alert alert-danger">
                                <b>Error:</b> New file name cannot be blank or match the name of an existing layout in your library.
                            </div>
                            {% endif %}
                            <form method="post" id="updateFileNameForm">
                                <div class="row">
                                    {% csrf_token %}
                                    <label for="id_new_file_name", class="form-label filename-label"><i class="bi bi-pencil-square"></i> Update file name:</label>
                                    {{ update_file_name_form.new_file_name }}
                                    <div class="col text-center mt-2">
                                        <button type="submit" class="btn btn-secondary btn-sm" style="width:20%">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    
                </div>

                <!-- Delete Button -->
                <div class="mt-3 text-end">
                    <form id="deleteForm" action="{% url 'delete_layout_test' layout.id %}" method="post">
                    {% csrf_token %}
                    <button type="button" class="btn btn-md btn-danger" onclick="confirmDelete()">Delete</button>
                    </form>
                </div>

            
        
        </div>
      </div>
    
    </div>

{% endblock %}

{% block scripting %}
    <script>
        function confirmDelete() {
        if (confirm("Are you sure you want to delete this layout from your library? This cannot be undone.")) {
            // If user confirms, submit the form
            document.getElementById("deleteForm").submit();
        } else {
            // If user cancels, do nothing
        }
    }
    </script>
{% endblock %}

templates/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Forgot Password</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static '../uploads/images/asset_primary_logo_tm.png' %}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="../static/layoutgenerator/css/styles.css" rel="stylesheet">
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: #007bff;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    label[for="email"] {
        margin-bottom: 10px;
    }

    .forgot-password-container {
      background-color: #fff;
      padding: 2%;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      text-align: center;
    }

    .company-logo {
    margin-bottom: 20px;
    }

    .company-logo img {
    max-width: 80%;
    height: auto;
    }

    .forgot-password-form {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    input[type="email"],
    button {
      width: 100%;
      padding: 10px;
      margin-bottom: 20px;
      border-radius: 3px;
      border: 1px solid #ccc;
    }

    button {
      background-color: #007bff;
      color: #fff;
      border: none;
      cursor: pointer;
    }

    button:hover {
      background-color: #0056b3;
    }

    p {
      margin-top: 15px;
      font-size: 14px;
    }

    a {
      color: #007bff;
      text-decoration: none;
    }

    a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <div class="forgot-password-container">
    <form method="post" class="forgot-password-form">
      {% csrf_token %}
        <h2>Forgot Password</h2>
        <div class="company-logo">
            <img src="https://www.asset-us.com/static/images/asset_primary_logo_tm.png" alt="Company Logo">
        </div>
        <label for="email">Emailio</label>
        <input type="email" placeholder="Email" id="email" name="email">
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <a href="{% url 'reset_password' %}">
          <button id="resetbutton" type="submit">Reset Password</button>
        </a>
        <p>Remembered your password? <a href="{% url 'login' %}" >Log in!</a></p>
    </form>
  </div>
</body>
</html>

templates/password_reset_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Forgot Password</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static '../uploads/images/asset_primary_logo_tm.png' %}" type="image/x-icon">
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
      <link href="../static/layoutgenerator/css/styles.css" rel="stylesheet">
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: #007bff;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    label[for="email"] {
        margin-bottom: 10px;
    }

    .forgot-password-container {
      background-color: #fff;
      padding: 2%;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      text-align: center;
    }

    .company-logo {
    margin-bottom: 20px;
    }

    .company-logo img {
    max-width: 80%;
    height: auto;
    }

    .forgot-password-form {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    input[type="email"],
    button {
      width: 100%;
      padding: 10px;
      margin-bottom: 20px;
      border-radius: 3px;
      border: 1px solid #ccc;
    }

    button {
      background-color: #007bff;
      color: #fff;
      border: none;
      cursor: pointer;
    }

    button:hover {
      background-color: #0056b3;
    }

    p {
      margin-top: 15px;
      font-size: 14px;
    }

    a {
      color: #007bff;
      text-decoration: none;
    }

    a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>

  <div class="container align-items-center justify-content-center">
    <center>
      <div class="forgot-password-container col-10 col-lg-5 align-self-center">
        <form method="post" class="forgot-password-form">
          <div class="company-logo">
              <img src="https://www.asset-us.com/static/images/asset_primary_logo_tm.png" alt="Company Logo">
          </div>
          <h6 class="mb-5">
              Password reset confirmed!
          </h6>
      </form>
      {% csrf_token %}
      <a href="{% url 'login' %}" >Return to Login</a>
      </div>
    </center>
  </div>
</body>